FROM stainless403/gui-base:latest
LABEL maintainer="stainless403"
LABEL description="MDCx容器化，内置了MDCx"

ENV APP_NAME        "MDCx Docker"
ENV APP_VERSION     "20230127"

# 复制应用文件到`/app`。文件路径示例：`app/MDCx_Main.py`
ADD app /app

WORKDIR /app

RUN python3.9 -m pip install --no-cache-dir -r requirements.txt -i https://pypi.douban.com/simple && \
    touch .initialized

# 容器启动时执行的脚本
COPY startapp.sh /startapp.sh