FROM jlesage/baseimage-gui:ubuntu-18.04-v4
LABEL maintainer="stainless403"
LABEL description="base on jlesage/baseimage-gui:ubuntu"

ENV APP_NAME        "TigerVNC APP"
ENV APP_VERSION     "0.0.0"
ENV USER_ID         0
ENV GROUP_ID        0
# 启用cjk字体（即Chinese-Japanese-Korean），以正常显示中文
ENV ENABLE_CJK_FONT 1
# 宽度(px)
ENV DISPLAY_WIDTH   "1200"
# 高度(px)
ENV DISPLAY_HEIGHT  "750"
# apt镜像
ENV APT_SOURCE_HOST "mirrors.ustc.edu.cn"

# 替换默认源，使用加速镜像
RUN sed -i "s/archive.ubuntu.com/${APT_SOURCE_HOST}/g" /etc/apt/sources.list
# 更新软件包
# RUN apt-get update -y && apt-get upgrade -y
RUN apt-get update -y

# 安装一些必须得软件包
RUN apt-get install -y curl locales libgl1 qt5-default
RUN export LANG=zh_CN.UTF-8 && locale-gen zh_CN.UTF-8

# 默认源只到python3.6，使用第三方源安装python3.9
RUN apt-get install -y software-properties-common && \
    # https://tooling.bennuttall.com/deadsnakes/ 添加源后更新一次源索引
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update -y

# 安装`pip`需要`python3.9-distutils`
RUN apt-get install -y python3.9-distutils python3.9 && \
    curl https://bootstrap.pypa.io/get-pip.py | python3.9