# syntax=docker/dockerfile:1.4

ARG BASE_IMAGE_TAG="v2-latest-pyqt6"

# 已编译应用的镜像tag
ARG MDCX_BIN_IMAGE_TAG="v2-latest-pyqt6"
FROM stainless403/build-mdcx:$MDCX_BIN_IMAGE_TAG AS provider


FROM stainless403/gui-base:$BASE_IMAGE_TAG

LABEL maintainer="stainless403"
LABEL description="base on stainless403/gui-base:$BASE_IMAGE_TAG"

ARG APP_NAME="MDCx"
ARG APP_VERSION="220260411_beta"

ENV APP_NAME $APP_NAME
ENV APP_VERSION $APP_VERSION

ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT

ARG BUILDPLATFORM
ARG BUILDOS
ARG BUILDARCH
ARG BUILDVARIANT

# 显示平台信息
RUN echo "-----Platform Information-----" && \
  echo "Target Platform: $TARGETPLATFORM ($TARGETOS/$TARGETARCH/$TARGETVARIANT)" && \
  echo "Build Platform: $BUILDPLATFORM ($BUILDOS/$BUILDARCH/$BUILDVARIANT)" && \
  echo "PYPI Mirror: $PYPI_MIRROR"

WORKDIR /app

ENV MDCX_CONFIG_PATH        "/mdcx-config"
ENV USER_HOME               "/config/home"

RUN mkdir -p "$MDCX_CONFIG_PATH" && \
  mkdir -p "$USER_HOME" && \
  chmod -R 777 /app && \
  chmod -R 777 "$MDCX_CONFIG_PATH"

# 写入默认的`配置文件目录`标记文件
RUN echo "$MDCX_CONFIG_PATH/config.v2.json" > /app/MDCx.config

# 复制已编译的文件
COPY --from=provider --chmod=+x /MDCx /app/MDCx

# TODO app icon
# RUN \
#   APP_ICON_URL=https://github.com/jlesage/docker-templates/raw/master/jlesage/images/generic-app-icon.png && \
#   install_app_icon.sh "$APP_ICON_URL"

COPY scripts/run-bin.sh /startapp.sh

COPY gui-base/rootfs/ /