# syntax=docker/dockerfile:1.4

ARG BASE_IMAGE_TAG="ubuntu-kde-22.04"

# 已编译应用的镜像tag
ARG MDCX_BIN_IMAGE_TAG="v2-latest-pyqt6"
FROM stainless403/build-mdcx:$MDCX_BIN_IMAGE_TAG AS provider


FROM stainless403/webtop-base:$BASE_IMAGE_TAG

LABEL maintainer="stainless403"
LABEL description="base on stainless403/webtop-base:$BASE_IMAGE_TAG"

ARG APP_NAME="MDCx"
ARG APP_VERSION="20230217"

ENV APP_NAME $APP_NAME
ENV APP_VERSION $APP_VERSION

ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT

ARG BUILDPLATFORM
ARG BUILDOS
ARG BUILDARCH
ARG BUILDVARIANT

# 输出构建信息
RUN echo "-----Image platform details:" && \
  echo "Target: $TARGETPLATFORM ($TARGETOS/$TARGETARCH/$TARGETVARIANT)" && \
  echo "Build: $BUILDPLATFORM ($BUILDOS/$BUILDARCH/$BUILDVARIANT)"

WORKDIR /app

ENV MDCX_APP_TYPE =         "bin"
ENV MDCX_CONFIG_PATH        "/mdcx-config"

RUN mkdir -p "$MDCX_CONFIG_PATH" && \
  chmod -R 777 /app && \
  chmod -R 777 "$MDCX_CONFIG_PATH"

# 写入默认的`配置文件目录`标记文件
RUN echo "$MDCX_CONFIG_PATH/config.v2.json" > /app/MDCx.config

# 复制已编译的文件
COPY --from=provider --chmod=+x /MDCx /app/MDCx


COPY webtop-base/rootfs /
COPY webtop-base/rootfs-builtin /

RUN ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime