# syntax=docker/dockerfile:1.4

ARG BASE_IMAGE_TAG="ubuntu-22.04"

# 已编译应用的镜像tag
ARG MDCX_BIN_IMAGE_TAG="latest"
FROM stainless403/build-mdcx:$MDCX_BIN_IMAGE_TAG as provider


FROM stainless403/webtop-base:$BASE_IMAGE_TAG

LABEL maintainer="stainless403"
LABEL description="base on stainless403/webtop-base:$BASE_IMAGE_TAG"

ARG APP_NAME="MDCx"
ARG APP_VERSION="20230217"

ENV APP_NAME $APP_NAME
ENV APP_VERSION $APP_VERSION

ARG TARGETPLATFORM
ARG TARGETOS
ARG TARGETARCH
ARG TARGETVARIANT

ARG BUILDPLATFORM
ARG BUILDOS
ARG BUILDARCH
ARG BUILDVARIANT

RUN echo "-----Image target platform details:"
RUN echo "TARGETPLATFORM    : $TARGETPLATFORM"
RUN echo "TARGETOS          : $TARGETOS"
RUN echo "TARGETARCH        : $TARGETARCH"
RUN echo "TARGETVARIANT     : $TARGETVARIANT"

RUN echo "-----Image build platform details:"
RUN echo "BUILDPLATFORM     : $BUILDPLATFORM"
RUN echo "BUILDOS           : $BUILDOS"
RUN echo "BUILDARCH         : $BUILDARCH"
RUN echo "BUILDVARIANT      : $BUILDVARIANT"

RUN apt-get update -y
RUN apt-get install unrar curl -y

WORKDIR /app

ENV MDCX_CONFIG_PATH        "/mdcx-config"

RUN mkdir -p "$MDCX_CONFIG_PATH" && \
  chmod -R 777 /app && \
  chmod -R 777 "$MDCX_CONFIG_PATH"

# 写入默认的`配置文件目录`标记文件
RUN echo "$MDCX_CONFIG_PATH/config.ini" > /app/MDCx.config

# 复制已编译的文件
COPY --from=provider /MDCx /app/MDCx

RUN chmod +x /app/MDCx

# 应用图标
COPY webtop-base/assets/logo.ico /app/logo.ico

# 桌面快捷方式
RUN mkdir -p /.app-assets/desktop
COPY webtop-base/assets/desktop/mdcx.desktop /.app-assets/desktop/
COPY webtop-base/assets/desktop/mdcx-config.desktop /.app-assets/desktop/
COPY webtop-base/assets/desktop/mdcx-logs.desktop /.app-assets/desktop/

COPY webtop-base/assets/rootfs /

RUN ln -fs /usr/share/zoneinfo/Asia/Shanghai /etc/localtime